
CC = gcc
CFLAGS = -g -Wall -std=c99
SOURCES = test_generator.c tests.c
OBJECTS = $(SOURCES:.c=.o)

test_generator.o: test_generator.c test_generator.h
	$(CC) $(CFLAGS) test_generator.c -c -o test_generator.o

tests.o: tests.c test_generator.h
	$(CC) $(CFLAGS) tests.c -c -o tests.o


tests: test_generator.o tests.o
	$(CC) $(CFLAGS) test_generator.o tests.o -o tests


.PHONY: clean

clean:
	rm edit $(OBJECTS)